name: heart_guard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.11.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  vibration: ^1.8.4 
  cupertino_icons: ^1.0.8
  telephony: ^0.2.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
